// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi7v5-TYlEQoCkqXMkpCLXPsibnP7V1As',
    appId: '1:705472924416:web:9afd3007e659aecad101e5',
    messagingSenderId: '705472924416',
    projectId: 'dalil-syria-1a31a',
    authDomain: 'dalil-syria-1a31a.firebaseapp.com',
    storageBucket: 'dalil-syria-1a31a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofi1A3O5VxNg0_4jgQtSRQR8s-w2aX6I',
    appId: '1:705472924416:android:2af05a8adfee2fded101e5',
    messagingSenderId: '705472924416',
    projectId: 'dalil-syria-1a31a',
    storageBucket: 'dalil-syria-1a31a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ZT7bncxryplrfWQOENSozN3auOtgKoU',
    appId: '1:705472924416:ios:5ec3379e82cd0a36d101e5',
    messagingSenderId: '705472924416',
    projectId: 'dalil-syria-1a31a',
    storageBucket: 'dalil-syria-1a31a.firebasestorage.app',
    iosBundleId: 'com.example.dalilSyria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6ZT7bncxryplrfWQOENSozN3auOtgKoU',
    appId: '1:705472924416:ios:5ec3379e82cd0a36d101e5',
    messagingSenderId: '705472924416',
    projectId: 'dalil-syria-1a31a',
    storageBucket: 'dalil-syria-1a31a.firebasestorage.app',
    iosBundleId: 'com.example.dalilSyria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi7v5-TYlEQoCkqXMkpCLXPsibnP7V1As',
    appId: '1:705472924416:web:05e2c456f15f9898d101e5',
    messagingSenderId: '705472924416',
    projectId: 'dalil-syria-1a31a',
    authDomain: 'dalil-syria-1a31a.firebaseapp.com',
    storageBucket: 'dalil-syria-1a31a.firebasestorage.app',
  );
}
